### ISSUE TITLE
训练完成后，怎么运行模型输出图片

### ISSUE THREAD

**Issue by WhiteWatson** [lee-zq/VesselSeg-Pytorch#9]
按照readme我已经训练并且测试完成了，但是请问想要输入视网膜图得到视网膜血管图应该怎么做？

**Comment by WhiteWatson** [comment]
windows运行test.py会有路径错误，已解决

**Comment by sujikun** [comment]
里面的sen、spe指标是如何算出来的

**Comment by sheoretic** [comment]
是的，如果在win上跑的话，需要修改test.py的第85行
save_img(total_img, os.path.join(self.save_img_path, "Result_" + str(i) + '.png'))
